[profile.default]
src = 'src'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge_cache'
solc = "0.8.18"
optimizer_runs = 1000000

[rpc_endpoints]
avalanche = "${AVALANCHE_RPC_URL}"
fuji = "${FUJI_RPC_URL}"