name: Open PR from Staging to Main

on:
  push:
    branches:
      - staging

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Set up Git user
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Merge staging into main
        run: |
          git checkout main
          git merge --no-ff staging
          git push origin main

      - name: Create Pull Request
        run: |
          curl \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pulls \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Merge staging into main",
              "body": "Automatically generated PR from the Github Action",
              "head": "staging",
              "base": "main"
            }'
