name: Automate Claim - Manual

on:
  schedule:
    - cron: '0 0 1-7 * 1' # Every Monday at 00:00 UTC

jobs:
  automated-claim:
    environment: production
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.DEPLOYER_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Compile project with Hardhat
        run: yarn hardhat compile

      - name: Execute Automated Claim task
        run: yarn hardhat automatedClaim --network avalanche
